config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :listings
  resources :orders
  root to: 'listings#index'
  post 'line_items/:id/create' => "line_items#create", as: "line_item_create"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sideqik"
    end



  get "/index", to: "listings#index"
  get "/new", to: "listings#new"
  get "/edit", to: "listings#edit"
  get "/show", to: "listings#show"
  get "/test", to: "listings#test"
  get "/checkout", to: 'listings#checkout'
  get "/search", to: "listings#search"   
  get '/cart/', to: "carts#show"
  get 'empty_cart', to: "carts#destroy"
  


end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :listings, through: :line_items
end

    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
      end
   

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :listing

   end

   
   
 

app/models/game_genre.rb
class GameGenre < ApplicationRecord
    belongs_to :games
    belongs_to :genres
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :game

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
    belongs_to :listing
    belongs_to :cart
    belongs_to :order, optional: true
  
    
    # def total_price
    #   self.quantity * self.product.price
    # end
  end
  

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user, optional: true
    has_one_attached :cover, dependent: :purge
    has_many :line_items, dependent: :destroy

    scope :active, ->{ where(status: "active") }
    scope :inactive, ->{ where(status: "inactive") }

    validates :gamename, presence: { message: "Please provide a game name" }
    validates :cover, presence: { message: "please provide a cover"}
    validates :price, presence: { message: "please provide a price"}
    validates :listingname, presence: { message: "please provide a listing name"}
    validates :genre, presence: { message: "Please provide a name" }
    
    def active?
        status == "active"
      end
    
      def inactive
        status == "inactive"
      end

    
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
end

app/models/platform.rb
class Platform < ApplicationRecord
    belongs_to :listings
end

app/models/post.rb
class Post < ApplicationRecord
    # has_many :games, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :set_role
  
  enum role: [:user, :admin]
  after_initialize do
    if self.new_record?
      self.role ||= :user
    end

end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :listings, dependent: :destroy 



# include DeviseTokenAuth::Concerns::ActiveRecordSupport
# include DeviseTokenAuth::Concerns::User
  def set_role
    self.add_role(:user) if self.role.nil?
  end

  def cart 
    return Cart.find_by(user_id: id, completed: false) || Cart.create(user_id: id, completed: false, price: 0)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

before_action :set_listing, only: [:update, :edit, :show, :destroy, :delete]   
before_action :authenticate_user!



def set_listing
  @listing = Listing.find(params[:id])  

end

def listing_params
  params.require(:listing).permit(:listingname, :cover, :price, :gamename, :genre)
end 

def index
    @listings = Listing.active
  
end

    def create
      @listing = Listing.new(listing_params)
      @listing.users_id = current_user.id
      begin
        @listing.save!
        redirect_to action: "index"
      end
    end
    
  def new
    @listing = Listing.new
    end

  def update
    @listing.update(listing_params)
    redirect_to @listing
  end

  def edit
    
  end


         
  def show
    @listing = Listing.find(params[:id])
    render :show
  end
  

end
  def destroy
       # Perform the lookup
       @listing = Listing.find(params[:id])
  begin
    @listing.destroy
    redirect_to action: "index"


  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
    def author_of(listing)
        user_signed_in? && listing.users_id == current_user.id
      end
    
      def admin?
        user_signed_in? && current_user.admin?
      end
    # //defines the admin/userid status of the user

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sub_total_helper.rb
module SubTotalHelper
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/helpers/testform_helper.rb
module TestformHelper
end

app/views/listings/_form.html.erb
<%= form_with model: @listing do |f| %> 

<div id="shadowbox">
  <%= f.label :Listing_name, class: "label" %>
<%= f.text_field :listingname, class: "input"%>

</div>
<div id="shadowbox">
    <%= f.label :Game, class: "label"%>
    <%= f.text_field :gamename, class: "input"%>

  </div>
  <div id="shadowbox">
  <%= f.label :Price, class: "label"%>
  <%= f.text_field :price, class: "input"%>
  </div>
    <div id="shadowbox">
     <%= f.label :Genre, class: "label"%>
   <%= f.text_field :genre, class: "input"%>
    </div>
  <div id="shadowbox">
<%= f.label :cover %>
<%= f.file_field :cover %>
</div>
   <p>
        <%= f.submit class: "btn-white" %>
    </p>    
    
    
    <% end %>

app/views/listings/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form', caption: "Save Changes" %>

app/views/listings/index.html.erb
<h1> Listings </h1>

<p>

<% @listings.index.each do |listing| %>
<div id="shadowbox">
<%= listing.status%>
 <p>Listing Name: <%=  listing.listingname %> </p>
 <p>Game Name: <%= listing.gamename%> </p>
 <p> Genre: <%= listing.genre %> </p>
  <p>Price: <%= listing.price %></p>
  
  <%if listing.cover.attached?%>
  <p><%= image_tag listing.cover, width: 150 %></p> 
  <% end %>
 
    <td><%= link_to "Show", listing_path(listing) %></td>
  
   

  
    <% end %>





<div>
</div>
</table>

app/views/listings/listing.html.erb
<h1>Create A new listing</h1>


<%# <%= render% 'form', listing: @listing %> 
<%= render 'form', caption: "new listing" %>
<% link_to /index%>
<% link_to /show %>

app/views/listings/new.html.erb
<h1>Create A new listing</h1>


<%# <%= render 'form', listing: @listing %> 
<%= render 'form', caption: "new listing" %>

app/views/listings/payment.html.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
  <span>Amount: $<%= @order.price %></span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="<%= @order.price %>"
  data-locale="auto"></script>
<% end %>

app/views/listings/show.html.erb
<div id="shadowbox">
<h1><%= @listing.listingname %></h1>
<h3>Price:<%= @listing.price %></h3>
<% if @listing.cover.attached? %>
    <%= image_tag @listing.cover, width: 150 %>
    <% end %>
 
<%=  button_to "Add to cart", line_item_create_path(@listing) %>
  <%# checks policy to see if user can edit or destroy %>
   <% if policy(@listing).destroy? %>
   <%= link_to "Edit", edit_listing_path(@listing) %>
  <%= button_to "Delete", @listing, :method => "delete" %>
<% end %>


</p>

 </div>
 

app/views/listings/test.html.erb
<h1>Books</h1>

<% if policy(Listing).new? %>
    <p><%= link_to "New listing", new_listing_path %></p>
<% end %>

<table>
    <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
    </tr>
   
</table>
    